### ISSUE TITLE
Feature Request: Edit Templates via WebUI

### ISSUE THREAD

**Issue by Miraculix1337** [JensForstmann/tmt2#22]
Hi,

is it possible to add the default Template before a match gets created?

**Comment by JensForstmann** [comment]
Hi,

Unfortunately, I do not understand your request. Can you explain in a bit more detail what you are trying to accomplish, what the frontend currently does, and what you would expect in your use case?

Since I'm currently reworking a few small things on the frontend anyway, I can possibly still consider this

**Comment by JensForstmann** [comment]
A system for saving & reusing presets is now included:

![image](https://github.com/JensForstmann/tmt2/assets/19289807/696b6356-d14f-4f76-99cc-4b53479e9caf)
